# Generated by Django 3.2.3 on 2021-05-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WFApp', '0002_alter_freq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freq',
            options={'ordering': ('freq_url',)},
        ),
    ]
