# Generated by Django 3.2.3 on 2021-05-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WFApp', '0004_alter_freq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freq',
            options={},
        ),
    ]
