# Generated by Django 3.2.3 on 2021-05-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WFApp', '0005_alter_freq_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='freq',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
